name: SCA + IaC Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "devsecops-node-app"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
      - uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.html

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install checkov
      - run: checkov -d . --output json > checkov.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov.json
